In [54]:
import pandas as pd
# Criando um DataFrame a partir de um dicionário 
#dataframes sao estruturas de dados bidimensionais, semelhantes a tabelas, que permitem armazenar e manipular dados de forma eficiente.
dados = {"nome": ["ana","bruno","carlos",],
         "idade": [25, 47, 32,],
         "cidade": ["são paulo", "rio de janeiro", "belo horizonte",],
        }
df = pd.DataFrame(dados)
print(df)

     nome  idade          cidade
0     ana     25       são paulo
1   bruno     47  rio de janeiro
2  carlos     32  belo horizonte

In [55]:
# Criando uma Series a partir de uma lista
#series sao estruturas de dados unidimensionais, semelhantes a uma coluna em uma tabela, que permitem armazenar e manipular dados de forma eficiente.
s = pd.Series([10, 20, 30, 40, 50])
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [56]:
# Lendo um arquivo CSV e criando um DataFrame
# O método read_csv() é usado para ler um arquivo CSV e criar um DataFrame a partir dos dados contidos no arquivo. O caminho do arquivo é passado como argumento para o método.
df = pd.read_csv('saude_mental_dados.csv')
df

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [57]:
# Exibindo as primeiras linhas do DataFrame
# O método head() é usado para exibir as primeiras linhas de um DataFrame. Por padrão, ele exibe as primeiras 5 linhas, mas você pode especificar o número de linhas a serem exibidas passando um argumento para o método.
df = pd.read_csv('saude_mental_dados.csv')
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

In [59]:
# Exibindo as primeiras linhas do DataFrame
# O método head() é usado para exibir as primeiras linhas de um DataFrame. Por padrão, ele exibe as primeiras 5 linhas, mas você pode especificar o número de linhas a serem exibidas passando um argumento para o método.
df = pd.read_csv('saude_mental_dados.csv')
df.tail()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0